aider: Fix setting 'words' attribute in 'find_range' function to create a new 'IPNetwork' object with the correct starting IP address.
# Aider chat conversation:

USER: I ran this command:

 cd bin && available-subnets 28 27 27 23

And got this output:

Traceback (most recent call last):
  File "/home/harleypig/projects/dotfiles/bin/available-subnets", line 140, in <module>
    main()
  File "/home/harleypig/projects/dotfiles/bin/available-subnets", line 132, in main
    subnets = open_subnets(args.base_range, args.used_subnets, args.ranges)
  File "/home/harleypig/projects/dotfiles/bin/available-subnets", line 80, in open_subnets
    new_range = find_range(base_range, taken_subnets, required_ips)
  File "/home/harleypig/projects/dotfiles/bin/available-subnets", line 55, in find_range
    start_ip.words = (start_ip.words[0], start_ip.words[1], start_ip.words[2], 0)
AttributeError: can't set attribute 'words'

ASSISTANT: The error you're encountering is due to trying to set the `words` attribute of an `IPAddress` object, which is not allowed. Instead, you should create a new `IPAddress` object with the modified octets. Here's the diff to fix the `find_range` function:

```diff
--- bin/available-subnets
+++ bin/available-subnets
@@ ... @@
 def find_range(base_range, taken_subnets, required_ips):
   available_ips = []
-  start_ip = base_range.ip
-  start_ip.words = (start_ip.words[0], start_ip.words[1], start_ip.words[2], 0)
-  base_range = IPNetwork(f"{start_ip}/{base_range.prefixlen}")
+  start_ip = IPNetwork(f"{base_range.network}/{base_range.prefixlen}")
+  start_ip.value += (1 << (32 - start_ip.prefixlen)) * (base_range.ip.words[2] % (1 << (8 - start_ip.prefixlen // 8)))

   for ip in base_range.iter_hosts():
     if any(ip in subnet for subnet in taken_subnets):
       available_ips = []
       continue

     elif len(available_ips) == required_ips:
       return available_ips

     else:
       available_ips.append(ip)

   raise ValueError("Not enough free space in the base range to accommodate the requested range.")
```

This change creates a new `IPNetwork` object with the correct starting IP address, which is calculated by adding the necessary value to the `start_ip.value` to align it with the beginning of the subnet defined by the third octet.